<a href="https://colab.research.google.com/github/SaadullahTariq/Artificial-Neural-Network/blob/main/NeuralNetwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
# First Neural Net
# Train, evaluate, and predict with the model
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt

mnist = keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
print(x_train.shape, y_train.shape)

# normalize: 0,255 -> 0,1
x_train, x_test = x_train / 255.0, x_test / 255.0

# model
model = keras.models.Sequential([
    keras.layers.Flatten(input_shape=(28,28)),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(10),
])

print(model.summary())

# another way to build the Sequential model:
#model = keras.models.Sequential()
#model.add(keras.layers.Flatten(input_shape=(28,28))
#model.add(keras.layers.Dense(128, activation='relu'))
#model.add(keras.layers.Dense(10))

# loss and optimizer
loss = keras.losses.SparseCategoricalCrossentropy(from_logits=True)
optim = keras.optimizers.Adam(lr=0.001)
metrics = ["accuracy"]

model.compile(loss=loss, optimizer=optim, metrics=metrics)

# training
batch_size = 64
epochs = 5

model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, shuffle=True, verbose=2)

# evaulate
model.evaluate(x_test, y_test, batch_size=batch_size, verbose=2)

# predictions

# 1. option: build new model with Softmax layer
probability_model = keras.models.Sequential([
    model,
    keras.layers.Softmax()
])

predictions = probability_model(x_test)
pred0 = predictions[0]
print(pred0)

# use np.argmax to get label with highest probability
label0 = np.argmax(pred0)
print(label0)

# 2. option: original model + nn.softmax, call model(x)
predictions = model(x_test)
predictions = tf.nn.softmax(predictions)
pred0 = predictions[0]
print(pred0)
label0 = np.argmax(pred0)
print(label0)

# 3. option: original model + nn.softmax, call model.predict(x)
predictions = model.predict(x_test, batch_size=batch_size)
predictions = tf.nn.softmax(predictions)
pred0 = predictions[0]
print(pred0)
label0 = np.argmax(pred0)
print(label0)

# call argmax for multiple labels
pred05s = predictions[0:5]
print(pred05s.shape)
label05s = np.argmax(pred05s, axis=1)
print(label05s)



(60000, 28, 28) (60000,)
Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_2 (Flatten)         (None, 784)               0         
                                                                 
 dense_4 (Dense)             (None, 128)               100480    
                                                                 
 dense_5 (Dense)             (None, 10)                1290      
                                                                 
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/5


/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


938/938 - 3s - loss: 0.3043 - accuracy: 0.9150 - 3s/epoch - 3ms/step
Epoch 2/5
938/938 - 2s - loss: 0.1369 - accuracy: 0.9600 - 2s/epoch - 2ms/step
Epoch 3/5
938/938 - 2s - loss: 0.0939 - accuracy: 0.9724 - 2s/epoch - 2ms/step
Epoch 4/5
938/938 - 2s - loss: 0.0728 - accuracy: 0.9781 - 2s/epoch - 3ms/step
Epoch 5/5
938/938 - 2s - loss: 0.0571 - accuracy: 0.9828 - 2s/epoch - 3ms/step
157/157 - 0s - loss: 0.0813 - accuracy: 0.9743 - 393ms/epoch - 3ms/step
tf.Tensor(
[1.3581891e-06 3.3774319e-09 3.1372398e-05 1.9045795e-04 7.3179024e-10
 3.2299361e-06 5.0362660e-13 9.9976641e-01 5.9212979e-08 7.1472737e-06], shape=(10,), dtype=float32)
7
tf.Tensor(
[1.3581891e-06 3.3774319e-09 3.1372398e-05 1.9045795e-04 7.3179024e-10
 3.2299361e-06 5.0362660e-13 9.9976641e-01 5.9212979e-08 7.1472737e-06], shape=(10,), dtype=float32)
7
tf.Tensor(
[1.3581891e-06 3.3774383e-09 3.1372456e-05 1.9045851e-04 7.3179302e-10
 3.2299454e-06 5.0362850e-13 9.9976641e-01 5.9213090e-08 7.1472873e-06], shape=(10,), dtype